title: ECOHCARE
subtitle: The Ecology of Medical Care in Austria
desc: ECOHCARE is the first study that assesses the health seeking behaviour of the whole Austrian population.
# sub-desc: ECOHCARE is the first study that assesses the health seeking behaviour of the whole Austrian population.

# disclaimer: Fußnoten...

name: Otto Pichlhöfer
email: otto.pichlhoefer@meduniwien.ac.at
github: https://github.com/ottopichlhoefer
twitter: https://twitter.com/docnord
# build config
# server: true
# auto: true
markdown: redcarpet

# RSS
name: ECOHCARE
url: ecohcare.at
author: Otto Pichlhöfer
copyright: Creative Commons Attribution-NoDerivs 3.0 Unported License
